// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TradePortal.Infrastructure.Data;

#nullable disable

namespace TradePortal.Infrastructure.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260223062343_AddReceiptPathToInvoice")]
    partial class AddReceiptPathToInvoice
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole<int>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("longtext");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<int>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("longtext");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("longtext");

                    b.Property<int>("RoleId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<int>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("longtext");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("longtext");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<int>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("longtext");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<int>", b =>
                {
                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.Property<int>("RoleId")
                        .HasColumnType("int");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<int>", b =>
                {
                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("Name")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("Value")
                        .HasColumnType("longtext");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("TradePortal.Domain.Entities.AuditLog", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("EntityId")
                        .HasColumnType("longtext");

                    b.Property<string>("EntityName")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("IpAddress")
                        .HasColumnType("longtext");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("NewValues")
                        .HasColumnType("longtext");

                    b.Property<string>("OldValues")
                        .HasColumnType("longtext");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("UserAgent")
                        .HasColumnType("longtext");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AuditLogs");
                });

            modelBuilder.Entity("TradePortal.Domain.Entities.BusinessPurpose", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ActivityCode")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)");

                    b.Property<int>("ActivityId")
                        .HasColumnType("int");

                    b.Property<string>("ActivityName")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("ApprovalRequirement")
                        .HasColumnType("longtext");

                    b.Property<string>("AuthorityName")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<string>("BranchCode")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("varchar(10)");

                    b.Property<int>("BranchId")
                        .HasColumnType("int");

                    b.Property<string>("BranchName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<string>("CategoryCode")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("varchar(10)");

                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.Property<string>("CategoryName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<string>("GroupCode")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("varchar(10)");

                    b.Property<int>("GroupId")
                        .HasColumnType("int");

                    b.Property<string>("GroupName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<string>("ISIC4Code")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)");

                    b.Property<string>("Icon")
                        .HasMaxLength(10)
                        .HasColumnType("varchar(10)");

                    b.Property<decimal?>("MinimumCapital")
                        .HasColumnType("decimal(65,30)");

                    b.Property<string>("SectionCode")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("varchar(10)");

                    b.Property<int>("SectionId")
                        .HasColumnType("int");

                    b.Property<string>("SectionName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<string>("SectorCode")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("varchar(10)");

                    b.Property<int>("SectorId")
                        .HasColumnType("int");

                    b.Property<string>("SectorName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.HasKey("Id");

                    b.ToTable("BusinessPurposes");
                });

            modelBuilder.Entity("TradePortal.Domain.Entities.ChecklistTemplate", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Description")
                        .HasColumnType("longtext");

                    b.Property<bool>("IsActive")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("IsMandatory")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("ItemNameAr")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.HasKey("Id");

                    b.ToTable("ChecklistTemplates");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2026, 2, 23, 6, 23, 42, 882, DateTimeKind.Utc).AddTicks(5887),
                            IsActive = true,
                            IsDeleted = false,
                            IsMandatory = true,
                            ItemNameAr = "صورة عن الهوية الشخصية للمؤسسين"
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTime(2026, 2, 23, 6, 23, 42, 882, DateTimeKind.Utc).AddTicks(6254),
                            IsActive = true,
                            IsDeleted = false,
                            IsMandatory = true,
                            ItemNameAr = "نظام التأسيس المقترح (موقع أصولاً)"
                        },
                        new
                        {
                            Id = 3,
                            CreatedAt = new DateTime(2026, 2, 23, 6, 23, 42, 882, DateTimeKind.Utc).AddTicks(6256),
                            IsActive = true,
                            IsDeleted = false,
                            IsMandatory = true,
                            ItemNameAr = "إيصال دفع الرسوم المالية"
                        },
                        new
                        {
                            Id = 4,
                            CreatedAt = new DateTime(2026, 2, 23, 6, 23, 42, 882, DateTimeKind.Utc).AddTicks(6257),
                            IsActive = true,
                            IsDeleted = false,
                            IsMandatory = true,
                            ItemNameAr = "صورة عن الختم الرسمي المعتمد"
                        },
                        new
                        {
                            Id = 5,
                            CreatedAt = new DateTime(2026, 2, 23, 6, 23, 42, 882, DateTimeKind.Utc).AddTicks(6258),
                            IsActive = true,
                            IsDeleted = false,
                            IsMandatory = false,
                            ItemNameAr = "سجل تجاري سابق (إن وجد)"
                        });
                });

            modelBuilder.Entity("TradePortal.Domain.Entities.CompanyType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("NameAr")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.HasKey("Id");

                    b.ToTable("CompanyTypes");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2026, 2, 23, 6, 23, 42, 882, DateTimeKind.Utc).AddTicks(4098),
                            IsActive = true,
                            IsDeleted = false,
                            NameAr = "شركة تضامن"
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTime(2026, 2, 23, 6, 23, 42, 882, DateTimeKind.Utc).AddTicks(4182),
                            IsActive = true,
                            IsDeleted = false,
                            NameAr = "شركة توصية بسيطة"
                        },
                        new
                        {
                            Id = 3,
                            CreatedAt = new DateTime(2026, 2, 23, 6, 23, 42, 882, DateTimeKind.Utc).AddTicks(4183),
                            IsActive = true,
                            IsDeleted = false,
                            NameAr = "شركة مساهمة عامة"
                        },
                        new
                        {
                            Id = 4,
                            CreatedAt = new DateTime(2026, 2, 23, 6, 23, 42, 882, DateTimeKind.Utc).AddTicks(4184),
                            IsActive = true,
                            IsDeleted = false,
                            NameAr = "شركة مساهمة مغفلة خاصة"
                        },
                        new
                        {
                            Id = 5,
                            CreatedAt = new DateTime(2026, 2, 23, 6, 23, 42, 882, DateTimeKind.Utc).AddTicks(4185),
                            IsActive = true,
                            IsDeleted = false,
                            NameAr = "شركة محدودة المسؤولية"
                        });
                });

            modelBuilder.Entity("TradePortal.Domain.Entities.Invoice", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("Amount")
                        .HasColumnType("decimal(65,30)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("InvoiceNum")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("IsPaid")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("ReceiptNum")
                        .HasColumnType("longtext");

                    b.Property<string>("ReceiptPath")
                        .HasColumnType("longtext");

                    b.Property<int>("RequestId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.HasKey("Id");

                    b.ToTable("Invoices");
                });

            modelBuilder.Entity("TradePortal.Domain.Entities.Notification", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("IsRead")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int?>("RequestId")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("RequestId");

                    b.HasIndex("UserId");

                    b.ToTable("Notifications");
                });

            modelBuilder.Entity("TradePortal.Domain.Entities.Province", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("NameAr")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("NameEn")
                        .HasColumnType("longtext");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.HasKey("Id");

                    b.ToTable("Provinces");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2026, 2, 23, 6, 23, 42, 881, DateTimeKind.Utc).AddTicks(9139),
                            IsActive = true,
                            IsDeleted = false,
                            NameAr = "دمشق"
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTime(2026, 2, 23, 6, 23, 42, 881, DateTimeKind.Utc).AddTicks(9383),
                            IsActive = true,
                            IsDeleted = false,
                            NameAr = "ريف دمشق"
                        },
                        new
                        {
                            Id = 3,
                            CreatedAt = new DateTime(2026, 2, 23, 6, 23, 42, 881, DateTimeKind.Utc).AddTicks(9384),
                            IsActive = true,
                            IsDeleted = false,
                            NameAr = "حلب"
                        },
                        new
                        {
                            Id = 4,
                            CreatedAt = new DateTime(2026, 2, 23, 6, 23, 42, 881, DateTimeKind.Utc).AddTicks(9385),
                            IsActive = true,
                            IsDeleted = false,
                            NameAr = "حمص"
                        },
                        new
                        {
                            Id = 5,
                            CreatedAt = new DateTime(2026, 2, 23, 6, 23, 42, 881, DateTimeKind.Utc).AddTicks(9386),
                            IsActive = true,
                            IsDeleted = false,
                            NameAr = "حماة"
                        },
                        new
                        {
                            Id = 6,
                            CreatedAt = new DateTime(2026, 2, 23, 6, 23, 42, 881, DateTimeKind.Utc).AddTicks(9386),
                            IsActive = true,
                            IsDeleted = false,
                            NameAr = "اللاذقية"
                        },
                        new
                        {
                            Id = 7,
                            CreatedAt = new DateTime(2026, 2, 23, 6, 23, 42, 881, DateTimeKind.Utc).AddTicks(9387),
                            IsActive = true,
                            IsDeleted = false,
                            NameAr = "طرطوس"
                        });
                });

            modelBuilder.Entity("TradePortal.Domain.Entities.ProvinceFeeRule", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("Amount")
                        .HasColumnType("decimal(65,30)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("FeeName")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<bool>("IsActive")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("tinyint(1)");

                    b.Property<int>("ProvinceId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.HasKey("Id");

                    b.HasIndex("ProvinceId");

                    b.ToTable("ProvinceFeeRules");
                });

            modelBuilder.Entity("TradePortal.Domain.Entities.Request", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("AuditorFeedback")
                        .HasColumnType("longtext");

                    b.Property<string>("CompanyName")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("CompanyTypeId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("ExtraDataJson")
                        .HasColumnType("json");

                    b.Property<int?>("InvoiceId")
                        .HasColumnType("int");

                    b.Property<string>("IpExpertFeedback")
                        .HasColumnType("longtext");

                    b.Property<int?>("IpExpertId")
                        .HasColumnType("int");

                    b.Property<string>("IpReportPath")
                        .HasColumnType("longtext");

                    b.Property<string>("IpVerdict")
                        .HasColumnType("longtext");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("tinyint(1)");

                    b.Property<DateTime?>("LockedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<int?>("LockedById")
                        .HasColumnType("int");

                    b.Property<string>("MainPdfPath")
                        .HasColumnType("longtext");

                    b.Property<string>("NameEn")
                        .HasColumnType("longtext");

                    b.Property<int>("ProvinceId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("RegistryDate")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("RegistryNumber")
                        .HasColumnType("longtext");

                    b.Property<DateTime?>("ReservationExpiryDate")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("StatusId")
                        .HasColumnType("int");

                    b.Property<int>("SubmitterId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.HasKey("Id");

                    b.HasIndex("CompanyTypeId");

                    b.HasIndex("InvoiceId")
                        .IsUnique();

                    b.HasIndex("IpExpertId");

                    b.HasIndex("LockedById");

                    b.HasIndex("ProvinceId");

                    b.HasIndex("StatusId");

                    b.HasIndex("SubmitterId");

                    b.ToTable("Requests");
                });

            modelBuilder.Entity("TradePortal.Domain.Entities.RequestAction", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ActionType")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("IsInternal")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Note")
                        .HasColumnType("longtext");

                    b.Property<int>("RequestId")
                        .HasColumnType("int");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("RequestId");

                    b.HasIndex("UserId");

                    b.ToTable("RequestActions");
                });

            modelBuilder.Entity("TradePortal.Domain.Entities.RequestBusinessPurpose", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("BusinessPurposeId")
                        .HasColumnType("int");

                    b.Property<string>("Complement")
                        .HasColumnType("longtext");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("tinyint(1)");

                    b.Property<int>("RequestId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.HasKey("Id");

                    b.HasIndex("BusinessPurposeId");

                    b.HasIndex("RequestId");

                    b.ToTable("RequestBusinessPurposes");
                });

            modelBuilder.Entity("TradePortal.Domain.Entities.RequestChecklist", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("FilePath")
                        .HasColumnType("longtext");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("IsProvided")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Notes")
                        .HasColumnType("longtext");

                    b.Property<int>("RequestId")
                        .HasColumnType("int");

                    b.Property<int>("TemplateId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.HasKey("Id");

                    b.HasIndex("RequestId");

                    b.HasIndex("TemplateId");

                    b.ToTable("RequestChecklists");
                });

            modelBuilder.Entity("TradePortal.Domain.Entities.RequestStatus", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ColorCode")
                        .HasColumnType("longtext");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("NameAr")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.HasKey("Id");

                    b.ToTable("RequestStatuses");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ColorCode = "blue",
                            CreatedAt = new DateTime(2026, 2, 23, 6, 23, 42, 882, DateTimeKind.Utc).AddTicks(3556),
                            IsActive = true,
                            IsDeleted = false,
                            NameAr = "جديد"
                        },
                        new
                        {
                            Id = 2,
                            ColorCode = "amber",
                            CreatedAt = new DateTime(2026, 2, 23, 6, 23, 42, 882, DateTimeKind.Utc).AddTicks(3779),
                            IsActive = true,
                            IsDeleted = false,
                            NameAr = "قيد التدقيق"
                        },
                        new
                        {
                            Id = 3,
                            ColorCode = "purple",
                            CreatedAt = new DateTime(2026, 2, 23, 6, 23, 42, 882, DateTimeKind.Utc).AddTicks(3780),
                            IsActive = true,
                            IsDeleted = false,
                            NameAr = "بانتظار رد حماية الملكية"
                        },
                        new
                        {
                            Id = 4,
                            ColorCode = "indigo",
                            CreatedAt = new DateTime(2026, 2, 23, 6, 23, 42, 882, DateTimeKind.Utc).AddTicks(3791),
                            IsActive = true,
                            IsDeleted = false,
                            NameAr = "تم الرد من حماية الملكية"
                        },
                        new
                        {
                            Id = 5,
                            ColorCode = "green",
                            CreatedAt = new DateTime(2026, 2, 23, 6, 23, 42, 882, DateTimeKind.Utc).AddTicks(3792),
                            IsActive = true,
                            IsDeleted = false,
                            NameAr = "مقبول"
                        },
                        new
                        {
                            Id = 6,
                            ColorCode = "red",
                            CreatedAt = new DateTime(2026, 2, 23, 6, 23, 42, 882, DateTimeKind.Utc).AddTicks(3793),
                            IsActive = true,
                            IsDeleted = false,
                            NameAr = "مرفوض"
                        },
                        new
                        {
                            Id = 7,
                            ColorCode = "orange",
                            CreatedAt = new DateTime(2026, 2, 23, 6, 23, 42, 882, DateTimeKind.Utc).AddTicks(3794),
                            IsActive = true,
                            IsDeleted = false,
                            NameAr = "بانتظار الدفع"
                        },
                        new
                        {
                            Id = 8,
                            ColorCode = "cyan",
                            CreatedAt = new DateTime(2026, 2, 23, 6, 23, 42, 882, DateTimeKind.Utc).AddTicks(3794),
                            IsActive = true,
                            IsDeleted = false,
                            NameAr = "قيد مراجعة مدير الشركات"
                        },
                        new
                        {
                            Id = 9,
                            ColorCode = "teal",
                            CreatedAt = new DateTime(2026, 2, 23, 6, 23, 42, 882, DateTimeKind.Utc).AddTicks(3795),
                            IsActive = true,
                            IsDeleted = false,
                            NameAr = "قيد مراجعة معاون الوزير"
                        },
                        new
                        {
                            Id = 10,
                            ColorCode = "emerald",
                            CreatedAt = new DateTime(2026, 2, 23, 6, 23, 42, 882, DateTimeKind.Utc).AddTicks(3796),
                            IsActive = true,
                            IsDeleted = false,
                            NameAr = "مقبول - حجز مؤقت"
                        },
                        new
                        {
                            Id = 11,
                            ColorCode = "rose",
                            CreatedAt = new DateTime(2026, 2, 23, 6, 23, 42, 882, DateTimeKind.Utc).AddTicks(3806),
                            IsActive = true,
                            IsDeleted = false,
                            NameAr = "حجز ملغى - لعدم استكمال التأسيس"
                        },
                        new
                        {
                            Id = 12,
                            ColorCode = "green",
                            CreatedAt = new DateTime(2026, 2, 23, 6, 23, 42, 882, DateTimeKind.Utc).AddTicks(3807),
                            IsActive = true,
                            IsDeleted = false,
                            NameAr = "حجز قطعي"
                        },
                        new
                        {
                            Id = 13,
                            ColorCode = "gray",
                            CreatedAt = new DateTime(2026, 2, 23, 6, 23, 42, 882, DateTimeKind.Utc).AddTicks(3808),
                            IsActive = true,
                            IsDeleted = false,
                            NameAr = "حجز ملغى - شطب"
                        },
                        new
                        {
                            Id = 14,
                            ColorCode = "purple",
                            CreatedAt = new DateTime(2026, 2, 23, 6, 23, 42, 882, DateTimeKind.Utc).AddTicks(3808),
                            IsActive = true,
                            IsDeleted = false,
                            NameAr = "تم الرد من القيادة"
                        });
                });

            modelBuilder.Entity("TradePortal.Domain.Entities.RolePermission", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Description")
                        .HasColumnType("longtext");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("PermissionKey")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("RoleId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.HasKey("Id");

                    b.ToTable("RolePermissions");
                });

            modelBuilder.Entity("TradePortal.Domain.Entities.SystemSetting", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Description")
                        .HasColumnType("longtext");

                    b.Property<string>("Group")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Key")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("SystemSettings");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2026, 2, 23, 6, 23, 42, 882, DateTimeKind.Utc).AddTicks(4383),
                            Description = "اسم المنصة الرئيسي",
                            Group = "General",
                            IsDeleted = false,
                            Key = "SiteName",
                            Value = "بوابة وزارة التجارة والتموين"
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTime(2026, 2, 23, 6, 23, 42, 882, DateTimeKind.Utc).AddTicks(4651),
                            Description = "بريد الدعم الفني",
                            Group = "General",
                            IsDeleted = false,
                            Key = "SupportEmail",
                            Value = "support@tradeportal.gov.sy"
                        },
                        new
                        {
                            Id = 3,
                            CreatedAt = new DateTime(2026, 2, 23, 6, 23, 42, 882, DateTimeKind.Utc).AddTicks(4653),
                            Description = "فتح باب التسجيل للشركات",
                            Group = "General",
                            IsDeleted = false,
                            Key = "RegistrationOpen",
                            Value = "true"
                        },
                        new
                        {
                            Id = 4,
                            CreatedAt = new DateTime(2026, 2, 23, 6, 23, 42, 882, DateTimeKind.Utc).AddTicks(4654),
                            Description = "وضع الصيانة (تعطيل الوصول للجميع عدا المدراء)",
                            Group = "Security",
                            IsDeleted = false,
                            Key = "MaintenanceMode",
                            Value = "false"
                        },
                        new
                        {
                            Id = 5,
                            CreatedAt = new DateTime(2026, 2, 23, 6, 23, 42, 882, DateTimeKind.Utc).AddTicks(4655),
                            Description = "تفعيل التحقق بخطوتين",
                            Group = "Security",
                            IsDeleted = false,
                            Key = "TwoFactorEnabled",
                            Value = "false"
                        },
                        new
                        {
                            Id = 6,
                            CreatedAt = new DateTime(2026, 2, 23, 6, 23, 42, 882, DateTimeKind.Utc).AddTicks(4656),
                            Description = "مدة الجلسة بالدقائق",
                            Group = "Security",
                            IsDeleted = false,
                            Key = "SessionTimeoutMinutes",
                            Value = "30"
                        },
                        new
                        {
                            Id = 7,
                            CreatedAt = new DateTime(2026, 2, 23, 6, 23, 42, 882, DateTimeKind.Utc).AddTicks(4656),
                            Description = "تفعيل إشعارات البريد الإلكتروني",
                            Group = "Notifications",
                            IsDeleted = false,
                            Key = "EnableEmailNotifications",
                            Value = "true"
                        },
                        new
                        {
                            Id = 8,
                            CreatedAt = new DateTime(2026, 2, 23, 6, 23, 42, 882, DateTimeKind.Utc).AddTicks(4657),
                            Description = "خادم البريد (SMTP)",
                            Group = "Notifications",
                            IsDeleted = false,
                            Key = "SmtpServer",
                            Value = "smtp.tradeportal.gov.sy"
                        },
                        new
                        {
                            Id = 9,
                            CreatedAt = new DateTime(2026, 2, 23, 6, 23, 42, 882, DateTimeKind.Utc).AddTicks(4658),
                            Description = "منفذ خادم البريد",
                            Group = "Notifications",
                            IsDeleted = false,
                            Key = "SmtpPort",
                            Value = "587"
                        },
                        new
                        {
                            Id = 10,
                            CreatedAt = new DateTime(2026, 2, 23, 6, 23, 42, 882, DateTimeKind.Utc).AddTicks(4659),
                            Description = "اسم مستخدم البريد",
                            Group = "Notifications",
                            IsDeleted = false,
                            Key = "SmtpUsername",
                            Value = "notifications@tradeportal.gov.sy"
                        },
                        new
                        {
                            Id = 11,
                            CreatedAt = new DateTime(2026, 2, 23, 6, 23, 42, 882, DateTimeKind.Utc).AddTicks(4660),
                            Description = "كلمة مرور البريد",
                            Group = "Notifications",
                            IsDeleted = false,
                            Key = "SmtpPassword",
                            Value = "********"
                        },
                        new
                        {
                            Id = 12,
                            CreatedAt = new DateTime(2026, 2, 23, 6, 23, 42, 882, DateTimeKind.Utc).AddTicks(4661),
                            Description = "اللون الأساسي للهوية",
                            Group = "Appearance",
                            IsDeleted = false,
                            Key = "PrimaryBrandColor",
                            Value = "#007A3D"
                        },
                        new
                        {
                            Id = 13,
                            CreatedAt = new DateTime(2026, 2, 23, 6, 23, 42, 882, DateTimeKind.Utc).AddTicks(4662),
                            Description = "اللون الثانوي للهوية",
                            Group = "Appearance",
                            IsDeleted = false,
                            Key = "SecondaryBrandColor",
                            Value = "#CE1126"
                        },
                        new
                        {
                            Id = 14,
                            CreatedAt = new DateTime(2026, 2, 23, 6, 23, 42, 882, DateTimeKind.Utc).AddTicks(4663),
                            Description = "رابط شعار الوزارة",
                            Group = "Appearance",
                            IsDeleted = false,
                            Key = "CustomLogoUrl",
                            Value = "/logo.png"
                        },
                        new
                        {
                            Id = 15,
                            CreatedAt = new DateTime(2026, 2, 23, 6, 23, 42, 882, DateTimeKind.Utc).AddTicks(4663),
                            Description = "الحد الأقصى لحجم الملفات المرفوعة",
                            Group = "Storage",
                            IsDeleted = false,
                            Key = "MaxFileSizeMB",
                            Value = "10"
                        },
                        new
                        {
                            Id = 16,
                            CreatedAt = new DateTime(2026, 2, 23, 6, 23, 42, 882, DateTimeKind.Utc).AddTicks(4664),
                            Description = "عدد أيام الحجز المؤقت قبل الإلغاء التلقائي",
                            Group = "Workflow",
                            IsDeleted = false,
                            Key = "ReservationExpiryDays",
                            Value = "7"
                        });
                });

            modelBuilder.Entity("TradePortal.Domain.Entities.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("longtext");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<bool>("IsActive")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("tinyint(1)");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("longtext");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("longtext");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("tinyint(1)");

                    b.Property<int?>("ProvinceId")
                        .HasColumnType("int");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("longtext");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex");

                    b.HasIndex("ProvinceId");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<int>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole<int>", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<int>", b =>
                {
                    b.HasOne("TradePortal.Domain.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<int>", b =>
                {
                    b.HasOne("TradePortal.Domain.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<int>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole<int>", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TradePortal.Domain.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<int>", b =>
                {
                    b.HasOne("TradePortal.Domain.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("TradePortal.Domain.Entities.AuditLog", b =>
                {
                    b.HasOne("TradePortal.Domain.Entities.User", "User")
                        .WithMany("AuditLogs")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("TradePortal.Domain.Entities.Notification", b =>
                {
                    b.HasOne("TradePortal.Domain.Entities.Request", "Request")
                        .WithMany()
                        .HasForeignKey("RequestId");

                    b.HasOne("TradePortal.Domain.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Request");

                    b.Navigation("User");
                });

            modelBuilder.Entity("TradePortal.Domain.Entities.ProvinceFeeRule", b =>
                {
                    b.HasOne("TradePortal.Domain.Entities.Province", "Province")
                        .WithMany()
                        .HasForeignKey("ProvinceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Province");
                });

            modelBuilder.Entity("TradePortal.Domain.Entities.Request", b =>
                {
                    b.HasOne("TradePortal.Domain.Entities.CompanyType", "CompanyType")
                        .WithMany("Requests")
                        .HasForeignKey("CompanyTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TradePortal.Domain.Entities.Invoice", "Invoice")
                        .WithOne("Request")
                        .HasForeignKey("TradePortal.Domain.Entities.Request", "InvoiceId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("TradePortal.Domain.Entities.User", "IpExpert")
                        .WithMany()
                        .HasForeignKey("IpExpertId");

                    b.HasOne("TradePortal.Domain.Entities.User", "LockedBy")
                        .WithMany("LockedRequests")
                        .HasForeignKey("LockedById")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("TradePortal.Domain.Entities.Province", "Province")
                        .WithMany("Requests")
                        .HasForeignKey("ProvinceId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("TradePortal.Domain.Entities.RequestStatus", "Status")
                        .WithMany("Requests")
                        .HasForeignKey("StatusId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TradePortal.Domain.Entities.User", "Submitter")
                        .WithMany("SubmitedRequests")
                        .HasForeignKey("SubmitterId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("CompanyType");

                    b.Navigation("Invoice");

                    b.Navigation("IpExpert");

                    b.Navigation("LockedBy");

                    b.Navigation("Province");

                    b.Navigation("Status");

                    b.Navigation("Submitter");
                });

            modelBuilder.Entity("TradePortal.Domain.Entities.RequestAction", b =>
                {
                    b.HasOne("TradePortal.Domain.Entities.Request", "Request")
                        .WithMany("History")
                        .HasForeignKey("RequestId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TradePortal.Domain.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Request");

                    b.Navigation("User");
                });

            modelBuilder.Entity("TradePortal.Domain.Entities.RequestBusinessPurpose", b =>
                {
                    b.HasOne("TradePortal.Domain.Entities.BusinessPurpose", "BusinessPurpose")
                        .WithMany()
                        .HasForeignKey("BusinessPurposeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("TradePortal.Domain.Entities.Request", "Request")
                        .WithMany("SelectedPurposes")
                        .HasForeignKey("RequestId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("BusinessPurpose");

                    b.Navigation("Request");
                });

            modelBuilder.Entity("TradePortal.Domain.Entities.RequestChecklist", b =>
                {
                    b.HasOne("TradePortal.Domain.Entities.Request", "Request")
                        .WithMany("ChecklistItems")
                        .HasForeignKey("RequestId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TradePortal.Domain.Entities.ChecklistTemplate", "Template")
                        .WithMany("RequestItems")
                        .HasForeignKey("TemplateId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Request");

                    b.Navigation("Template");
                });

            modelBuilder.Entity("TradePortal.Domain.Entities.User", b =>
                {
                    b.HasOne("TradePortal.Domain.Entities.Province", "Province")
                        .WithMany("Users")
                        .HasForeignKey("ProvinceId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Province");
                });

            modelBuilder.Entity("TradePortal.Domain.Entities.ChecklistTemplate", b =>
                {
                    b.Navigation("RequestItems");
                });

            modelBuilder.Entity("TradePortal.Domain.Entities.CompanyType", b =>
                {
                    b.Navigation("Requests");
                });

            modelBuilder.Entity("TradePortal.Domain.Entities.Invoice", b =>
                {
                    b.Navigation("Request")
                        .IsRequired();
                });

            modelBuilder.Entity("TradePortal.Domain.Entities.Province", b =>
                {
                    b.Navigation("Requests");

                    b.Navigation("Users");
                });

            modelBuilder.Entity("TradePortal.Domain.Entities.Request", b =>
                {
                    b.Navigation("ChecklistItems");

                    b.Navigation("History");

                    b.Navigation("SelectedPurposes");
                });

            modelBuilder.Entity("TradePortal.Domain.Entities.RequestStatus", b =>
                {
                    b.Navigation("Requests");
                });

            modelBuilder.Entity("TradePortal.Domain.Entities.User", b =>
                {
                    b.Navigation("AuditLogs");

                    b.Navigation("LockedRequests");

                    b.Navigation("SubmitedRequests");
                });
#pragma warning restore 612, 618
        }
    }
}
