// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TradePortal.Infrastructure.Data;

#nullable disable

namespace TradePortal.Infrastructure.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260214092644_AddChecklistSeed")]
    partial class AddChecklistSeed
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole<int>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("longtext");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<int>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("longtext");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("longtext");

                    b.Property<int>("RoleId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<int>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("longtext");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("longtext");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<int>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("longtext");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<int>", b =>
                {
                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.Property<int>("RoleId")
                        .HasColumnType("int");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<int>", b =>
                {
                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("Name")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("Value")
                        .HasColumnType("longtext");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("TradePortal.Domain.Entities.AuditLog", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("EntityId")
                        .HasColumnType("longtext");

                    b.Property<string>("EntityName")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("IpAddress")
                        .HasColumnType("longtext");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("NewValues")
                        .HasColumnType("longtext");

                    b.Property<string>("OldValues")
                        .HasColumnType("longtext");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("UserAgent")
                        .HasColumnType("longtext");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AuditLogs");
                });

            modelBuilder.Entity("TradePortal.Domain.Entities.ChecklistTemplate", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Description")
                        .HasColumnType("longtext");

                    b.Property<bool>("IsActive")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("IsMandatory")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("ItemNameAr")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.HasKey("Id");

                    b.ToTable("ChecklistTemplates");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2026, 2, 14, 9, 26, 44, 122, DateTimeKind.Utc).AddTicks(8913),
                            IsActive = true,
                            IsDeleted = false,
                            IsMandatory = true,
                            ItemNameAr = "صورة عن الهوية الشخصية للمؤسسين"
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTime(2026, 2, 14, 9, 26, 44, 122, DateTimeKind.Utc).AddTicks(9124),
                            IsActive = true,
                            IsDeleted = false,
                            IsMandatory = true,
                            ItemNameAr = "نظام التأسيس المقترح (موقع أصولاً)"
                        },
                        new
                        {
                            Id = 3,
                            CreatedAt = new DateTime(2026, 2, 14, 9, 26, 44, 122, DateTimeKind.Utc).AddTicks(9125),
                            IsActive = true,
                            IsDeleted = false,
                            IsMandatory = true,
                            ItemNameAr = "إيصال دفع الرسوم المالية"
                        },
                        new
                        {
                            Id = 4,
                            CreatedAt = new DateTime(2026, 2, 14, 9, 26, 44, 122, DateTimeKind.Utc).AddTicks(9126),
                            IsActive = true,
                            IsDeleted = false,
                            IsMandatory = true,
                            ItemNameAr = "صورة عن الختم الرسمي المعتمد"
                        },
                        new
                        {
                            Id = 5,
                            CreatedAt = new DateTime(2026, 2, 14, 9, 26, 44, 122, DateTimeKind.Utc).AddTicks(9127),
                            IsActive = true,
                            IsDeleted = false,
                            IsMandatory = false,
                            ItemNameAr = "سجل تجاري سابق (إن وجد)"
                        });
                });

            modelBuilder.Entity("TradePortal.Domain.Entities.CompanyType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("NameAr")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.HasKey("Id");

                    b.ToTable("CompanyTypes");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2026, 2, 14, 9, 26, 44, 122, DateTimeKind.Utc).AddTicks(7391),
                            IsActive = true,
                            IsDeleted = false,
                            NameAr = "شركة تضامن"
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTime(2026, 2, 14, 9, 26, 44, 122, DateTimeKind.Utc).AddTicks(7464),
                            IsActive = true,
                            IsDeleted = false,
                            NameAr = "شركة توصية بسيطة"
                        },
                        new
                        {
                            Id = 3,
                            CreatedAt = new DateTime(2026, 2, 14, 9, 26, 44, 122, DateTimeKind.Utc).AddTicks(7465),
                            IsActive = true,
                            IsDeleted = false,
                            NameAr = "شركة مساهمة عامة"
                        },
                        new
                        {
                            Id = 4,
                            CreatedAt = new DateTime(2026, 2, 14, 9, 26, 44, 122, DateTimeKind.Utc).AddTicks(7466),
                            IsActive = true,
                            IsDeleted = false,
                            NameAr = "شركة مساهمة مغفلة خاصة"
                        },
                        new
                        {
                            Id = 5,
                            CreatedAt = new DateTime(2026, 2, 14, 9, 26, 44, 122, DateTimeKind.Utc).AddTicks(7467),
                            IsActive = true,
                            IsDeleted = false,
                            NameAr = "شركة محدودة المسؤولية"
                        });
                });

            modelBuilder.Entity("TradePortal.Domain.Entities.Province", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("NameAr")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("NameEn")
                        .HasColumnType("longtext");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.HasKey("Id");

                    b.ToTable("Provinces");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2026, 2, 14, 9, 26, 44, 122, DateTimeKind.Utc).AddTicks(3281),
                            IsActive = true,
                            IsDeleted = false,
                            NameAr = "دمشق"
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTime(2026, 2, 14, 9, 26, 44, 122, DateTimeKind.Utc).AddTicks(3530),
                            IsActive = true,
                            IsDeleted = false,
                            NameAr = "ريف دمشق"
                        },
                        new
                        {
                            Id = 3,
                            CreatedAt = new DateTime(2026, 2, 14, 9, 26, 44, 122, DateTimeKind.Utc).AddTicks(3531),
                            IsActive = true,
                            IsDeleted = false,
                            NameAr = "حلب"
                        },
                        new
                        {
                            Id = 4,
                            CreatedAt = new DateTime(2026, 2, 14, 9, 26, 44, 122, DateTimeKind.Utc).AddTicks(3532),
                            IsActive = true,
                            IsDeleted = false,
                            NameAr = "حمص"
                        },
                        new
                        {
                            Id = 5,
                            CreatedAt = new DateTime(2026, 2, 14, 9, 26, 44, 122, DateTimeKind.Utc).AddTicks(3533),
                            IsActive = true,
                            IsDeleted = false,
                            NameAr = "حماة"
                        },
                        new
                        {
                            Id = 6,
                            CreatedAt = new DateTime(2026, 2, 14, 9, 26, 44, 122, DateTimeKind.Utc).AddTicks(3534),
                            IsActive = true,
                            IsDeleted = false,
                            NameAr = "اللاذقية"
                        },
                        new
                        {
                            Id = 7,
                            CreatedAt = new DateTime(2026, 2, 14, 9, 26, 44, 122, DateTimeKind.Utc).AddTicks(3534),
                            IsActive = true,
                            IsDeleted = false,
                            NameAr = "طرطوس"
                        });
                });

            modelBuilder.Entity("TradePortal.Domain.Entities.Request", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("AuditorFeedback")
                        .HasColumnType("longtext");

                    b.Property<string>("CompanyName")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("CompanyTypeId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("ExtraDataJson")
                        .HasColumnType("json");

                    b.Property<string>("IpReportPath")
                        .HasColumnType("longtext");

                    b.Property<string>("IpVerdict")
                        .HasColumnType("longtext");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("tinyint(1)");

                    b.Property<DateTime?>("LockedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<int?>("LockedById")
                        .HasColumnType("int");

                    b.Property<string>("MainPdfPath")
                        .HasColumnType("longtext");

                    b.Property<int>("ProvinceId")
                        .HasColumnType("int");

                    b.Property<int>("StatusId")
                        .HasColumnType("int");

                    b.Property<int>("SubmitterId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.HasKey("Id");

                    b.HasIndex("CompanyTypeId");

                    b.HasIndex("LockedById");

                    b.HasIndex("ProvinceId");

                    b.HasIndex("StatusId");

                    b.HasIndex("SubmitterId");

                    b.ToTable("Requests");
                });

            modelBuilder.Entity("TradePortal.Domain.Entities.RequestChecklist", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("FilePath")
                        .HasColumnType("longtext");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("IsProvided")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Notes")
                        .HasColumnType("longtext");

                    b.Property<int>("RequestId")
                        .HasColumnType("int");

                    b.Property<int>("TemplateId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.HasKey("Id");

                    b.HasIndex("RequestId");

                    b.HasIndex("TemplateId");

                    b.ToTable("RequestChecklists");
                });

            modelBuilder.Entity("TradePortal.Domain.Entities.RequestStatus", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ColorCode")
                        .HasColumnType("longtext");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("NameAr")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.HasKey("Id");

                    b.ToTable("RequestStatuses");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ColorCode = "blue",
                            CreatedAt = new DateTime(2026, 2, 14, 9, 26, 44, 122, DateTimeKind.Utc).AddTicks(6957),
                            IsActive = true,
                            IsDeleted = false,
                            NameAr = "جديد"
                        },
                        new
                        {
                            Id = 2,
                            ColorCode = "amber",
                            CreatedAt = new DateTime(2026, 2, 14, 9, 26, 44, 122, DateTimeKind.Utc).AddTicks(7149),
                            IsActive = true,
                            IsDeleted = false,
                            NameAr = "قيد التدقيق"
                        },
                        new
                        {
                            Id = 3,
                            ColorCode = "purple",
                            CreatedAt = new DateTime(2026, 2, 14, 9, 26, 44, 122, DateTimeKind.Utc).AddTicks(7150),
                            IsActive = true,
                            IsDeleted = false,
                            NameAr = "بانتظار رد حماية الملكية"
                        },
                        new
                        {
                            Id = 4,
                            ColorCode = "indigo",
                            CreatedAt = new DateTime(2026, 2, 14, 9, 26, 44, 122, DateTimeKind.Utc).AddTicks(7152),
                            IsActive = true,
                            IsDeleted = false,
                            NameAr = "تم الرد من حماية الملكية"
                        },
                        new
                        {
                            Id = 5,
                            ColorCode = "green",
                            CreatedAt = new DateTime(2026, 2, 14, 9, 26, 44, 122, DateTimeKind.Utc).AddTicks(7153),
                            IsActive = true,
                            IsDeleted = false,
                            NameAr = "مقبول"
                        },
                        new
                        {
                            Id = 6,
                            ColorCode = "red",
                            CreatedAt = new DateTime(2026, 2, 14, 9, 26, 44, 122, DateTimeKind.Utc).AddTicks(7154),
                            IsActive = true,
                            IsDeleted = false,
                            NameAr = "مرفوض"
                        });
                });

            modelBuilder.Entity("TradePortal.Domain.Entities.SystemSetting", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Description")
                        .HasColumnType("longtext");

                    b.Property<string>("Group")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Key")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("SystemSettings");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2026, 2, 14, 9, 26, 44, 122, DateTimeKind.Utc).AddTicks(7644),
                            Description = "اسم المنصة الرئيسي",
                            Group = "General",
                            IsDeleted = false,
                            Key = "SiteName",
                            Value = "بوابة وزارة التجارة والتموين"
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTime(2026, 2, 14, 9, 26, 44, 122, DateTimeKind.Utc).AddTicks(7906),
                            Description = "وضع الصيانة",
                            Group = "Security",
                            IsDeleted = false,
                            Key = "MaintenanceMode",
                            Value = "false"
                        },
                        new
                        {
                            Id = 3,
                            CreatedAt = new DateTime(2026, 2, 14, 9, 26, 44, 122, DateTimeKind.Utc).AddTicks(7908),
                            Description = "فتح باب التسجيل",
                            Group = "General",
                            IsDeleted = false,
                            Key = "RegistrationOpen",
                            Value = "true"
                        },
                        new
                        {
                            Id = 4,
                            CreatedAt = new DateTime(2026, 2, 14, 9, 26, 44, 122, DateTimeKind.Utc).AddTicks(7909),
                            Description = "الحد الأقصى لحجم الملفات",
                            Group = "Storage",
                            IsDeleted = false,
                            Key = "MaxFileSizeMB",
                            Value = "10"
                        });
                });

            modelBuilder.Entity("TradePortal.Domain.Entities.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("longtext");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<bool>("IsActive")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("tinyint(1)");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("longtext");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("longtext");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("tinyint(1)");

                    b.Property<int?>("ProvinceId")
                        .HasColumnType("int");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("longtext");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex");

                    b.HasIndex("ProvinceId");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<int>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole<int>", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<int>", b =>
                {
                    b.HasOne("TradePortal.Domain.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<int>", b =>
                {
                    b.HasOne("TradePortal.Domain.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<int>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole<int>", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TradePortal.Domain.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<int>", b =>
                {
                    b.HasOne("TradePortal.Domain.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("TradePortal.Domain.Entities.AuditLog", b =>
                {
                    b.HasOne("TradePortal.Domain.Entities.User", "User")
                        .WithMany("AuditLogs")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("TradePortal.Domain.Entities.Request", b =>
                {
                    b.HasOne("TradePortal.Domain.Entities.CompanyType", "CompanyType")
                        .WithMany("Requests")
                        .HasForeignKey("CompanyTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TradePortal.Domain.Entities.User", "LockedBy")
                        .WithMany("LockedRequests")
                        .HasForeignKey("LockedById")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("TradePortal.Domain.Entities.Province", "Province")
                        .WithMany("Requests")
                        .HasForeignKey("ProvinceId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("TradePortal.Domain.Entities.RequestStatus", "Status")
                        .WithMany("Requests")
                        .HasForeignKey("StatusId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TradePortal.Domain.Entities.User", "Submitter")
                        .WithMany("SubmitedRequests")
                        .HasForeignKey("SubmitterId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("CompanyType");

                    b.Navigation("LockedBy");

                    b.Navigation("Province");

                    b.Navigation("Status");

                    b.Navigation("Submitter");
                });

            modelBuilder.Entity("TradePortal.Domain.Entities.RequestChecklist", b =>
                {
                    b.HasOne("TradePortal.Domain.Entities.Request", "Request")
                        .WithMany("ChecklistItems")
                        .HasForeignKey("RequestId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TradePortal.Domain.Entities.ChecklistTemplate", "Template")
                        .WithMany("RequestItems")
                        .HasForeignKey("TemplateId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Request");

                    b.Navigation("Template");
                });

            modelBuilder.Entity("TradePortal.Domain.Entities.User", b =>
                {
                    b.HasOne("TradePortal.Domain.Entities.Province", "Province")
                        .WithMany("Users")
                        .HasForeignKey("ProvinceId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Province");
                });

            modelBuilder.Entity("TradePortal.Domain.Entities.ChecklistTemplate", b =>
                {
                    b.Navigation("RequestItems");
                });

            modelBuilder.Entity("TradePortal.Domain.Entities.CompanyType", b =>
                {
                    b.Navigation("Requests");
                });

            modelBuilder.Entity("TradePortal.Domain.Entities.Province", b =>
                {
                    b.Navigation("Requests");

                    b.Navigation("Users");
                });

            modelBuilder.Entity("TradePortal.Domain.Entities.Request", b =>
                {
                    b.Navigation("ChecklistItems");
                });

            modelBuilder.Entity("TradePortal.Domain.Entities.RequestStatus", b =>
                {
                    b.Navigation("Requests");
                });

            modelBuilder.Entity("TradePortal.Domain.Entities.User", b =>
                {
                    b.Navigation("AuditLogs");

                    b.Navigation("LockedRequests");

                    b.Navigation("SubmitedRequests");
                });
#pragma warning restore 612, 618
        }
    }
}
